version: 2

project_name: tess

before:
  hooks:
    - go mod tidy

builds:
  - id: tess
    main: ./cmd
    env:
      - CGO_ENABLED=0
    goos: [darwin]
    goarch: [arm64]
    ldflags:
      - -s -w -X tess/internal.Version={{.Version}}

archives:
  - id: archive
    ids: [tess]
    formats: [tar.gz]
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_v{{ .Version }}'
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums_v{{ .Version }}.txt'

brews:
  - name: tess
    repository:
      owner: vigetlabs
      name: homebrew-taps
    directory: Formula
    description: Generate Lattice review summaries; optional Drive upload via rclone.
    homepage: https://github.com/vigetlabs/tess
    license: "" # internal-use; omit or set if you later add a license
    dependencies:
      - name: rclone
      - name: pandoc
      - name: tectonic
    test: |
      system "#{bin}/tess", "--help"
    install: |
      bin.install "tess"
    commit_author:
      name: tess-bot
      email: noreply@viget.com

release:
  draft: false
  prerelease: false
